import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import i18n from '@/lib/i18n'; // Import i18n
import { useState, useEffect } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [language, setLanguage] = useState(i18n.language);
  useEffect(() => {
    i18n.on('languageChanged', (lng) => setLanguage(lng));
  }, []);
  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'ha' : 'en';
    i18n.changeLanguage(newLanguage);
    localStorage.setItem('i18nextLng', newLanguage); // Save preference
    console.log('Language preference saved:', newLanguage); // Debugging log
  };

  return (
    <html lang={language}>
      <head>
        {/* Google Analytics */}
        <script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');
            `,
          }}
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-blue-500 text-white p-4">TailwindCSS Test</div>{' '}
        {/* Test element */}
        <header className="fixed top-4 right-4 z-50 bg-red-500 p-4 rounded-lg shadow-lg">
          <button
            onClick={toggleLanguage}
            className="px-4 py-2 bg-gray-800 text-white rounded-lg shadow-md hover:bg-gray-700 transition"
          >
            {language === 'en' ? 'Hausa' : 'English'}
          </button>
        </header>
        {/* Add button */}
        <button className="map-button">Click Me</button>
        {children}
      </body>
    </html>
  );
}
