export const pharmacies = [
  {
    id: 'c1',
    name: 'ActonMed Pharmacy',
    lga: 'FCT',
    address: 'Market Rd, Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1488126,
    longitude: 7.3220055,
  },
  {
    id: 'c2',
    name: 'Apogee Pharmacy & Stores',
    lga: 'FCT',
    address:
      'Apogee Pharmacy & Stores 2, Buar Close, Beside Jevinik Restaurant, Off Ademola Adetokunbo Street, Bangui Street, Wuse II, Wuse, Abuja, Federal Capital Territory 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0689384,
    longitude: 7.4817075,
  },
  {
    id: 'c3',
    name: 'Apogee Pharmacy Kubwa',
    lga: 'FCT',
    address: '47 Gado Nasko Rd, Kubwa 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.151227,
    longitude: 7.331385,
  },
  {
    id: 'c4',
    name: 'Ascle Plus Pharmacy',
    lga: 'FCT',
    address:
      'Ascle - Plus Pharmacy & Stores 2922+7R7, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0006659,
    longitude: 7.3520499,
  },
  {
    id: 'c5',
    name: 'Bamak Pharm. Chemists & Stores ltd',
    lga: 'FCT',
    address:
      'House 8, Zone D, Apo Resettlement, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0081606,
    longitude: 7.4774478,
  },
  {
    id: 'c6',
    name: 'Bamak Pharmacy',
    lga: 'FCT',
    address:
      'Abuja Shopping Mall Wuse zone 3 Wuse zone 3 Abuja manicipal, Zone 3, 8 Maputo St, Wuse, Abuja 900001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0603672,
    longitude: 7.4688679,
  },
  {
    id: 'c7',
    name: 'Bari Pharmacy',
    lga: 'FCT',
    address:
      'Bari Pharmacy, Kuduru Along Bwari road, 79W3+2W5, Bwari 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.2950039,
    longitude: 7.3548636,
  },
  {
    id: 'c8',
    name: 'Becan Pharmacyd',
    lga: 'FCT',
    address:
      'Becan Pharmacy Suite A4 Sherif Plaza, Aminu Kano Crescent, Wuse II, Abuja, FCT, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0829426,
    longitude: 7.4679474,
  },
  {
    id: 'c9',
    name: 'Beedaglaz Pharmacy',
    lga: 'FCT',
    address:
      'BEEDAGLAZ PHARMACY JIKWOYI Jikwoyi Rd, Abuja 900109, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9491519,
    longitude: 7.5497684,
  },
  {
    id: 'c10',
    name: 'Befit Pharmacy',
    lga: 'FCT',
    address:
      'Chika junction XCV3+GPG, Airport Rd, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9938097,
    longitude: 7.4043148,
  },
  {
    id: 'c11',
    name: 'Beta Pharmacy',
    lga: 'FCT',
    address:
      'Area 2 Shopping Complex Moshood Abiola Rd, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0356843,
    longitude: 7.4778649,
  },
  {
    id: 'c12',
    name: 'Biogenes pharmacy Ltd',
    lga: 'FCT',
    address:
      'BIOGENES PHARMACY Shop 50, FHA Cornershops, Opposite Custom Quarters, Site, New Karu 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9926856,
    longitude: 7.5724627,
  },
  {
    id: 'c13',
    name: 'BLOMAC-SURE PHARMACY AND STORES',
    lga: 'FCT',
    address:
      'SHM Complex 3FH2+X3P, Mabushi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0798714,
    longitude: 7.4501456,
  },
  {
    id: 'c14',
    name: 'Boral Pharmacy',
    lga: 'FCT',
    address: 'Dutse Police Signboard Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1677467,
    longitude: 7.378925,
  },
  {
    id: 'c15',
    name: 'Bristol Pharmacy',
    lga: 'FCT',
    address: '44 1st Ave 44 1st Ave, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0423559,
    longitude: 7.3929607,
  },
  {
    id: 'c16',
    name: 'C-Nergy Pharmacy',
    lga: 'FCT',
    address: 'Arab Road Arab Rd, Kubwa 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1563016,
    longitude: 7.3099986,
  },
  {
    id: 'c17',
    name: 'Cameb pharmacy',
    lga: 'FCT',
    address: '4FMM+HG6, Mape 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1339125,
    longitude: 7.4837656,
  },
  {
    id: 'c18',
    name: 'Care angels',
    lga: 'FCT',
    address:
      'Adetokunbo Ademola Crescent Adetokunbo Ademola Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0768939,
    longitude: 7.4874809,
  },
  {
    id: 'c19',
    name: 'CARECYCLE PHARMACY',
    lga: 'FCT',
    address:
      'CareCycle Pharmacy 112 Panaf Dr, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1380277,
    longitude: 7.3838851,
  },
  {
    id: 'c20',
    name: 'Cell Rich Pharmacy',
    lga: 'FCT',
    address: '7 General Hospital Rd, Kuje 900105, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8806205,
    longitude: 7.2316136,
  },
  {
    id: 'c21',
    name: 'Chabelton Pharmacy',
    lga: 'FCT',
    address: '3CWR+2M2 3CWR+2M2, Ndawuse 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0950125,
    longitude: 7.4416406,
  },
  {
    id: 'c22',
    name: 'Cheferron Pharmacy',
    lga: 'FCT',
    address:
      'Nyanya before the bridge AMAC, Karu, Abuja 100001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9927796,
    longitude: 7.5724622,
  },
  {
    id: 'c23',
    name: 'Chidivac Pharmacy',
    lga: 'FCT',
    address: 'Lugbe Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9640864,
    longitude: 7.3813708,
  },
  {
    id: 'c24',
    name: 'Christahealth-Medix Pharmacy LTD',
    lga: 'FCT',
    address:
      'Jeremiah Useni Road Jeremiah Useni Rd, Kutunku 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9242164,
    longitude: 7.0747618,
  },
  {
    id: 'c25',
    name: 'Chumelac Pharmacy and stores ltd',
    lga: 'FCT',
    address:
      'Fudie Mall 3CCM+R5G, Mike Akhigbe Way, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0720701,
    longitude: 7.4329673,
  },
  {
    id: 'c26',
    name: 'Ciems Fortune Pharmacy',
    lga: 'FCT',
    address:
      'I.C World Emporia Centre Ishaya Shekari Crescent, Gwarinpa Estate, Gwarinpa 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1106346,
    longitude: 7.4218677,
  },
  {
    id: 'c27',
    name: 'City Mart Pharmacy',
    lga: 'FCT',
    address:
      'Fidelity Bank (Gwagwalada) 21, Specialist Hospital Road, Gwagwalada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9512103,
    longitude: 7.0641661,
  },
  {
    id: 'c28',
    name: 'Claudio Pharmacy',
    lga: 'FCT',
    address:
      'Kado Estate Kado Estate, Jabi, Gwarinpa 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0827629,
    longitude: 7.4151536,
  },
  {
    id: 'c29',
    name: 'Cleron Pharmacy and stores',
    lga: 'FCT',
    address:
      'Cleron Pharmacy & Stores LTD V6MH+4W7, Secretariat Rd, Kuje 900105, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8827774,
    longitude: 7.2297988,
  },
  {
    id: 'c30',
    name: 'Cleva Pharmacy & Daily Needs Ltd',
    lga: 'FCT',
    address:
      '32 A.E. Ekukinam St 32 A.E. Ekukinam St, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0667325,
    longitude: 7.441159,
  },
  {
    id: 'c31',
    name: 'Clickx pharmacy',
    lga: 'FCT',
    address:
      'Clickx Pharmacy. Aminu Kano Crescent. 3FPC+3C3, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0851318,
    longitude: 7.4710527,
  },
  {
    id: 'c32',
    name: 'Cmargs Pharmacy',
    lga: 'FCT',
    address:
      'First Avenue Efab Estate, House 180 1st Ave, Lokogoma, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9695425,
    longitude: 7.4564546,
  },
  {
    id: 'c33',
    name: 'CMargs Pharmacy & Wellmart Lokogoma Plaza',
    lga: 'FCT',
    address:
      'CMargs Pharmacy & Wellmart Plot 80, G2, G3 Lokogoma Rd, Lokogoma, Abuja 900109, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9903785,
    longitude: 7.4476057,
  },
  {
    id: 'c34',
    name: 'CNR Pharmacy and Stores',
    lga: 'FCT',
    address:
      'Cnr Pharmacy & Stores Kubwa, 901101, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1489528,
    longitude: 7.3083121,
  },
  {
    id: 'c35',
    name: 'Co-fran pharmacy',
    lga: 'FCT',
    address:
      '21 Samuel Ladoke Akintola Boulevard 21 Samuel Ladoke Akintola Boulevard, Garki, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0225642,
    longitude: 7.4956627,
  },
  {
    id: 'c36',
    name: 'Cosmos Pharmacy',
    lga: 'FCT',
    address: 'I.K P STORES LUGBE Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9866319,
    longitude: 7.3623754,
  },
  {
    id: 'c37',
    name: 'CRESS PHARMACEUTICALS LTD',
    lga: 'FCT',
    address:
      'Bwari Express Road Bwari Express Rd, Kubwa 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1407082,
    longitude: 7.3682006,
  },
  {
    id: 'c38',
    name: 'Daros Pharmacy',
    lga: 'FCT',
    address:
      'Nymex Plaza by 2nd Gate Junction, Gado Nasko, Way, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1427435,
    longitude: 7.3230504,
  },
  {
    id: 'c39',
    name: 'Datura Pharmacy Abuja',
    lga: 'FCT',
    address: 'Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9606426,
    longitude: 7.4165053,
  },
  {
    id: 'c40',
    name: 'De Primo Pharmacy and stores 1',
    lga: 'FCT',
    address:
      'De-Primo Pharmacy & Stores 2HGP+PCC, Abacha Rd, Ado 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9618144,
    longitude: 7.6765816,
  },
  {
    id: 'c41',
    name: 'De wonders Pharmacy',
    lga: 'FCT',
    address:
      'Moremi Restaurant Area 3, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0292947,
    longitude: 7.4800633,
  },
  {
    id: 'c42',
    name: 'De-Primo Pharmacy and Stores',
    lga: 'Nasarawa',
    address: 'Abacha Road Abacha Rd, Mararaba, Ado, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9618144,
    longitude: 7.6765816,
  },
  {
    id: 'c43',
    name: 'Defash pharmacy',
    lga: 'FCT',
    address:
      'Games Village Estate Islamic Foundation No.1 Fifth Ave, Kaura, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0156468,
    longitude: 7.4470487,
  },
  {
    id: 'c44',
    name: 'Delas Pharmacy',
    lga: 'Nasarawa',
    address:
      'Delas Pharmacy 24,Masaka By Uturn Nassarawa State, Keffin/Wambai 961102, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8471213,
    longitude: 7.8776023,
  },
  {
    id: 'c45',
    name: 'Delina Pharmacy',
    lga: 'Nasarawa',
    address: 'DELINA PHARMACY Ado 961105, Nasarawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9987833,
    longitude: 7.6376662,
  },
  {
    id: 'c46',
    name: 'Demo Pharmacy',
    lga: 'FCT',
    address:
      'DEMOS PHARMACY AND STORES Jimoh R. Badamosi Street, 2 Kpaduma, Extension, Gudu, Abuja 900001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0148194,
    longitude: 7.5210308,
  },
  {
    id: 'c47',
    name: 'Dependable Pharmacy',
    lga: 'FCT',
    address:
      'Mabushi Ultra Modern Market Kado, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0932033,
    longitude: 7.4429197,
  },
  {
    id: 'c48',
    name: 'DFD Pharmacy and Stores',
    lga: 'FCT',
    address:
      'zone 6, 1 Yaounde St zone 6, 1 Yaounde St, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0696037,
    longitude: 7.4526298,
  },
  {
    id: 'c49',
    name: 'Diaba Pharmacy Ltd',
    lga: 'Nasarawa',
    address: 'Midland Plaza Mararaba Keffi Express Way, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0285068,
    longitude: 7.596071,
  },
  {
    id: 'c50',
    name: 'DOKSAB PHARMACY LTD',
    lga: 'FCT',
    address:
      'Arisfa Plaza 2H8Q+R6F, Old Karu Rd, Mararaba, New Karu 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0170687,
    longitude: 7.5880517,
  },
  {
    id: 'c51',
    name: 'Dollar Pharmacy',
    lga: 'FCT',
    address:
      'Dollar Pharmacy Limited 37 Julius Nyerere Cres, Asokoro, Aso 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0437971,
    longitude: 7.5235632,
  },
  {
    id: 'c52',
    name: 'Dominago Pharmacy & Stores',
    lga: 'FCT',
    address: '2 1st Avenue, Gwarinpa, 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.091082,
    longitude: 7.4137915,
  },
  {
    id: 'c53',
    name: 'Dominago Pharmacy & Stores - Gwagwalada',
    lga: 'FCT',
    address:
      'X34J+FR2, Gwagwalada-Dukwa Rd, Gwagwalada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9517239,
    longitude: 7.0815533,
  },
  {
    id: 'c54',
    name: 'DonaRose Pharmacy',
    lga: 'FCT',
    address:
      'White House White House, 79 Adetokunbo Ademola Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0693077,
    longitude: 7.4808032,
  },
  {
    id: 'c55',
    name: 'Drug flow Chemist',
    lga: 'FCT',
    address:
      'Dutse Market 1 Bwari Express Rd, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1378541,
    longitude: 7.3674328,
  },
  {
    id: 'c56',
    name: 'Drug Haven Pharmacy',
    lga: 'FCT',
    address:
      '22 A.E. Ekukinam St 22 A.E. Ekukinam St, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0667325,
    longitude: 7.441159,
  },
  {
    id: 'c57',
    name: 'DrugLane Pharmacy',
    lga: 'FCT',
    address:
      '90 Kwame Nkrumah Cres 90 Kwame Nkrumah Cres, Asokoro, Aso 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0427889,
    longitude: 7.5281766,
  },
  {
    id: 'c58',
    name: 'Drugtrack Pharmacy',
    lga: 'FCT',
    address: 'Shop A04 Lugbe Plaza, Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9909433,
    longitude: 7.3551127,
  },
  {
    id: 'c59',
    name: 'Dubinson Pharmacy',
    lga: 'FCT',
    address:
      'Dubinson Pharmaceuticals Limited 1 Angola St, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0592277,
    longitude: 7.4654003,
  },
  {
    id: 'c60',
    name: 'E-Palms Pharmacy Ltd.',
    lga: 'FCT',
    address:
      "E-Palms Pharmacy House 24, 1(A) Rd, FHA, opposite Lord's Chosen Charismatic Church, Lugbe, Along Airport Road, Iddo Tudunwada 900101, Federal Capital Territory",
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9764669,
    longitude: 7.3712741,
  },
  {
    id: 'c61',
    name: 'Eazylink Pharmacy and Resources Ltd',
    lga: 'FCT',
    address:
      'Code Of Conduct Tribunal, Jabi, Abuja Plot 89, Sector Centre B, Cadastral Zone B 16,, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0556352,
    longitude: 7.4299495,
  },
  {
    id: 'c62',
    name: 'ELIEL PHARMACY AND STORES LTD',
    lga: 'FCT',
    address:
      '46 Julius Nyerere Cres, Asokoro, Aso 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0443861,
    longitude: 7.5230532,
  },
  {
    id: 'c63',
    name: 'Elixir Pharmacy',
    lga: 'FCT',
    address:
      'Elixir Pharmaceutical Ltd 1, Murg Shopping Mall, Akwa Street, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0368409,
    longitude: 7.4856078,
  },
  {
    id: 'c64',
    name: 'Ellavina Pharmacy',
    lga: 'FCT',
    address:
      'Befs Plaza 21 Ajose Adeogun St, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0693493,
    longitude: 7.4431013,
  },
  {
    id: 'c65',
    name: 'Elot Pharmacy',
    lga: 'FCT',
    address:
      'DBM plaza 3FJ7+4VX, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0803617,
    longitude: 7.464748,
  },
  {
    id: 'c66',
    name: 'Elot Pharmacy Apo',
    lga: 'FCT',
    address:
      'Apo Urban Market APO RESETTLEMENT AREA, Plot 116 zone A, Abuja 900104, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9825757,
    longitude: 7.4991763,
  },
  {
    id: 'c67',
    name: 'ElRophi Pharmacy and Stores',
    lga: 'FCT',
    address:
      'Central Mosque Sabon Lugbe, Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9471508,
    longitude: 7.3368031,
  },
  {
    id: 'c68',
    name: 'Em-Zik pharmacy & Supermarket',
    lga: 'FCT',
    address:
      'Em-Zik Pharmacy & Supermarket Ltd Lugbe Zone 5, Along Airport Road, Lugbe, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9758112,
    longitude: 7.3731401,
  },
  {
    id: 'c69',
    name: 'EMDOR PHARMACY',
    lga: 'FCT',
    address: 'Lingu Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.071223,
    longitude: 7.4674425,
  },
  {
    id: 'c70',
    name: 'Emmitex Medical Store',
    lga: 'FCT',
    address:
      'His Grace Pavilion Estate, Apo-Wumba His Grace Pavilion Estate, Apo-Wumba, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9668559,
    longitude: 7.4863656,
  },
  {
    id: 'c71',
    name: 'ERIBEK PHARMACY',
    lga: 'FCT',
    address:
      'W3MR+VPC, beside Wazobia Park, Dagiri, Gwagwalada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9290167,
    longitude: 7.0915132,
  },
  {
    id: 'c72',
    name: 'Esoma Pharmacy',
    lga: 'FCT',
    address: 'XCJR+W6M, 5b Okonni Cl, Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9820973,
    longitude: 7.4393397,
  },
  {
    id: 'c73',
    name: 'Euchel Pharmacy',
    lga: 'FCT',
    address:
      'Euchel Pharmacy & Store Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1657875,
    longitude: 7.3240781,
  },
  {
    id: 'c74',
    name: 'Everyday-24 Pharmacy & Stores',
    lga: 'FCT',
    address:
      '14 Ahmadu Bello Wy, opp. Eddy-Vic Hotel 14 Ahmadu Bello Wy, opp. Eddy-Vic Hotel, Garki 2, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0296219,
    longitude: 7.4937225,
  },
  {
    id: 'c75',
    name: 'EVERYDAY-24 PHARMACY & STORES LTD',
    lga: 'FCT',
    address:
      'MKK Plaza MKK Plaza, Abdulsalami Abubakar Rd, Gudu, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0008359,
    longitude: 7.4720833,
  },
  {
    id: 'c76',
    name: 'Family Pharmacy',
    lga: 'FCT',
    address:
      '124 Aminu Kano Cres 124 Aminu Kano Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.083656,
    longitude: 7.46967,
  },
  {
    id: 'c77',
    name: 'Fanett Pharmacy',
    lga: 'FCT',
    address: 'Guzape Guzape, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0117252,
    longitude: 7.5079538,
  },
  {
    id: 'c78',
    name: 'Filial Pharmacy Ltd',
    lga: 'FCT',
    address: 'Lugbe Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9640864,
    longitude: 7.3813708,
  },
  {
    id: 'c79',
    name: 'Fitmas Pharmacy',
    lga: 'FCT',
    address: 'Madalla Madalla, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1018441,
    longitude: 7.2167511,
  },
  {
    id: 'c80',
    name: 'Fittamas Pharmacy',
    lga: 'FCT',
    address: 'Madalla 902101, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1018441,
    longitude: 7.2167511,
  },
  {
    id: 'c81',
    name: 'FLORENS PHARMACY',
    lga: 'FCT',
    address:
      'Evergreen Mall Durumi, Phase II, Kubwa 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0210945,
    longitude: 7.4556357,
  },
  {
    id: 'c82',
    name: 'Framak Pharmacy',
    lga: 'FCT',
    address: 'Moit Guest Inn Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9750731,
    longitude: 7.3763064,
  },
  {
    id: 'c83',
    name: 'G & C Pharmacy',
    lga: 'FCT',
    address:
      '3 Ayangba St 3 Ayangba St, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.04586,
    longitude: 7.4967972,
  },
  {
    id: 'c84',
    name: 'G & I',
    lga: 'FCT',
    address: 'Abia Street Abia St, Karu 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9895987,
    longitude: 7.556137,
  },
  {
    id: 'c85',
    name: 'G-World Pharmacy',
    lga: 'FCT',
    address:
      'plot 81, 81 Gado Nasko Rd plot 81, 81 Gado Nasko Rd, Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1464716,
    longitude: 7.3237603,
  },
  {
    id: 'c86',
    name: 'Gahf Pharmacy',
    lga: 'FCT',
    address: 'Nyanya, Ado 900101, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0126306,
    longitude: 7.5572231,
  },
  {
    id: 'c87',
    name: 'Gama Pharmacy',
    lga: 'FCT',
    address: 'Tunga Maje Tunga Maje 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0556272,
    longitude: 7.1924968,
  },
  {
    id: 'c88',
    name: 'Garima Pharmacy and stores',
    lga: 'FCT',
    address:
      'Garima Pharmacy &Stores Garima plaza, Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1410347,
    longitude: 7.3048653,
  },
  {
    id: 'c89',
    name: 'Glittering Stones Pharmacy',
    lga: 'FCT',
    address:
      'Glittering Stones Pharmacy and Stores Area 3, Tafawa Balewa Rd, opp. Sharon Ultimate Hotels, Garki, Abuja 900104, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0297901,
    longitude: 7.4840278,
  },
  {
    id: 'c90',
    name: 'Glostin Care Pharmacy LTD',
    lga: 'FCT',
    address:
      'Abia House , Abuja Abia House , Abuja, First Ave, Wuse, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0663417,
    longitude: 7.4926636,
  },
  {
    id: 'c91',
    name: 'God is Able Pharmacy',
    lga: 'Nasarawa',
    address: 'XM2H+7C5, Abuja - Keffi Expy, New Nyanya 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9157489,
    longitude: 7.7081354,
  },
  {
    id: 'c92',
    name: 'Great Shepherd Pharmacy Ltd.',
    lga: 'FCT',
    address:
      'Abia Line Transport Company 3C6J+J4X, Bimbo Akintola, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0616202,
    longitude: 7.4303484,
  },
  {
    id: 'c93',
    name: 'GREEN FOREST PHARMACY',
    lga: 'FCT',
    address:
      'Green Forest Pharmacy Plot 171 Adetokunbo Ademola Cres, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.080502,
    longitude: 7.4855884,
  },
  {
    id: 'c94',
    name: 'Green Horizon Pharmacy',
    lga: 'Nasarawa',
    address: 'New, Nyanya Rd, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9526607,
    longitude: 7.6738023,
  },
  {
    id: 'c95',
    name: 'Green Park Pharmacy',
    lga: 'FCT',
    address:
      'Hausa Market X9R3+47W Presbyterian Church St, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9903732,
    longitude: 7.3532168,
  },
  {
    id: 'c96',
    name: 'Green Park Pharmacy',
    lga: 'FCT',
    address:
      'X9R3+47W Presbyterian Church St, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.991182,
    longitude: 7.3531706,
  },
  {
    id: 'c97',
    name: 'Guild Pharmacy',
    lga: 'FCT',
    address:
      'Guild Pharma Obafemi Awolowo Way Abuja Abuja Municipal, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.065284,
    longitude: 7.429913,
  },
  {
    id: 'c98',
    name: 'Hajjo Yawo Pharmacy',
    lga: 'Adamawa',
    address: 'Jimeta, 640101, Adamawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.2716518,
    longitude: 12.4528907,
  },
  {
    id: 'c99',
    name: 'Hakuri Pharmacy Bekaji',
    lga: 'Adamawa',
    address: '80 Mohammed Mustafa Road, Jimeta, 640102, Adamawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.2797299,
    longitude: 12.4584676,
  },
  {
    id: 'c100',
    name: 'Hakuri Pharmacy Jimeta',
    lga: 'Adamawa',
    address: '80 Mohammed Mustafa Road, Jimeta, 640102, Adamawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.2797299,
    longitude: 12.4584676,
  },
  {
    id: 'c101',
    name: 'Hawil Pharmacy',
    lga: 'FCT',
    address:
      'Hawil PHARMACY LTD zoological garden, Mustajad St, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0316667,
    longitude: 7.4729659,
  },
  {
    id: 'c102',
    name: 'Health Bank Pharmacy',
    lga: 'FCT',
    address:
      'Health Bank Pharmacy And Products Nig. Ltd Gidan Mangoro Junction, Karshi Rd, off Orozo, ABUJA 900109, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0562646,
    longitude: 7.4985259,
  },
  {
    id: 'c103',
    name: 'HealthCamp',
    lga: 'FCT',
    address:
      'Gwagwalada Road Gwagwalada Rd, Gwagwalada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9605093,
    longitude: 7.0606563,
  },
  {
    id: 'c104',
    name: 'Healthcare Medical',
    lga: 'FCT',
    address: 'Airport Road Airport Rd, Abuja, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9450526,
    longitude: 7.2872428,
  },
  {
    id: 'c105',
    name: 'Healthplus',
    lga: 'FCT',
    address:
      'HealthPlus Pharmacy Shop 13A Ceddi Plaza, Plot 264 Tafawa Balewa Way(Close to CBN, Central Business Dis, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0550646,
    longitude: 7.4895426,
  },
  {
    id: 'c106',
    name: 'Healthtree pharmacy ltd',
    lga: 'FCT',
    address: '29 3rd Ave 29 3rd Ave, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0613226,
    longitude: 7.3988302,
  },
  {
    id: 'c107',
    name: 'Healthtrust Pharmacy',
    lga: 'FCT',
    address:
      '40 Lingu Cres 40 Lingu Cres, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0720093,
    longitude: 7.4692831,
  },
  {
    id: 'c108',
    name: 'Healthy C pharmacy',
    lga: 'FCT',
    address:
      'Plot no 556 london road1, off arab road kubwa abuja 1 Arab Rd, Kubwa 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1562234,
    longitude: 7.3100128,
  },
  {
    id: 'c109',
    name: 'Horsepower Pharmacy',
    lga: 'Nasarawa',
    address: 'Uac Rd, Lafia 950101, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.5196694,
    longitude: 8.5081945,
  },
  {
    id: 'c110',
    name: 'IC World Pharmacy',
    lga: 'FCT',
    address: '2nd Avenue 2nd Ave, Gwarinpa 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1130784,
    longitude: 7.4215833,
  },
  {
    id: 'c111',
    name: 'Intak Pharmaceutical',
    lga: 'FCT',
    address:
      '23 A.E. Ekukinam St 23 A.E. Ekukinam St, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0667325,
    longitude: 7.441159,
  },
  {
    id: 'c112',
    name: 'Irochi Pharmacy',
    lga: 'FCT',
    address:
      'Irochi Pharmacy and Supermarket Police sign board road, beside Remaco filling station, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9747805,
    longitude: 7.3627865,
  },
  {
    id: 'c113',
    name: 'JACHDEZ PHARMACY LTD. APO ABUJA',
    lga: 'FCT',
    address:
      'Plot AT175, third gate, Apo mechanic estate, Apo, Abuja, Abuja 900104, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9595875,
    longitude: 7.4978433,
  },
  {
    id: 'c114',
    name: 'JACHDEZ PHARMACY LTD. KUBWA, ABUJA',
    lga: 'FCT',
    address: '55 Aliero Cres, Kubwa 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1485239,
    longitude: 7.3356007,
  },
  {
    id: 'c115',
    name: 'Jade HealthCare Ltd',
    lga: 'Nasarawa',
    address: 'XMMG+W4M, New Karu 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9848375,
    longitude: 7.6752969,
  },
  {
    id: 'c116',
    name: 'Jahban Pharmacy',
    lga: 'FCT',
    address: 'Jahban PHARMACY Garki 2, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0276198,
    longitude: 7.4949471,
  },
  {
    id: 'c117',
    name: 'Jalel Pharmacy',
    lga: 'FCT',
    address:
      'Jalel Bio Clinical services LTD 13 Crushrock layout, Jabi, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0759809,
    longitude: 7.4110988,
  },
  {
    id: 'c118',
    name: 'Jearm Pharmacy',
    lga: 'FCT',
    address:
      'Okitipupa Crescent Okitipupa Cres, Kubwa 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1578745,
    longitude: 7.3416164,
  },
  {
    id: 'c119',
    name: 'Jearm Pharmacy',
    lga: 'FCT',
    address:
      'Jearm Pharmacy Ltd 584Q+7F3, Okitipupa Cres, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1556375,
    longitude: 7.3386719,
  },
  {
    id: 'c120',
    name: 'Jethro Pharmacy',
    lga: 'FCT',
    address:
      'Jethro Pharmacy & Superstores 84 Yakubu Gowon Cres, Asokoro, Aso 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0454647,
    longitude: 7.5267901,
  },
  {
    id: 'c121',
    name: 'Jimeta Central Pharmacy',
    lga: 'Adamawa',
    address: 'Jimeta, 640102, Adamawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.2533789,
    longitude: 12.4667204,
  },
  {
    id: 'c122',
    name: 'Joelola Pharmacy',
    lga: 'FCT',
    address:
      'Plot 809, 810 Dahiru Musdafa Blvd, Wuye, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0411358,
    longitude: 7.436382,
  },
  {
    id: 'c123',
    name: 'Jomed Pharmacy',
    lga: 'FCT',
    address:
      'XGH3+78C, Apo Resettlement, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9781875,
    longitude: 7.5032656,
  },
  {
    id: 'c124',
    name: 'Jonik Pharmacy',
    lga: 'FCT',
    address: 'Efab Mall Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0436385,
    longitude: 7.5037779,
  },
  {
    id: 'c125',
    name: 'Jonik Pharmacy',
    lga: 'FCT',
    address: 'Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0318959,
    longitude: 7.4828122,
  },
  {
    id: 'c126',
    name: 'Jonmed pharmaceutical ltd',
    lga: 'FCT',
    address:
      'Abia House , Abuja Abia House , Abuja, First Ave, Wuse, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0663417,
    longitude: 7.4926636,
  },
  {
    id: 'c127',
    name: 'K C Pharmacy',
    lga: 'FCT',
    address:
      'Fortis Microfinance Bank - Garki Village Branch 38 Samuel Ladoke Akintola Boulevard, Garki 2, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0213214,
    longitude: 7.4888362,
  },
  {
    id: 'c128',
    name: 'K-Beek Pharmacy',
    lga: 'FCT',
    address:
      'K-beek Pharmacy Opposite gwagwalada market, Gwagwalada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9400914,
    longitude: 7.0759899,
  },
  {
    id: 'c129',
    name: 'KAJANE PHARMACY',
    lga: 'FCT',
    address:
      '1 Kangole St, behind City College Road 1 Kangole St, behind City College Road, Karu, Ado 900001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0003533,
    longitude: 7.5823719,
  },
  {
    id: 'c130',
    name: 'Keecee Pharmacy',
    lga: 'FCT',
    address:
      'KeeCee Pharmacy Kabusa XC2V+CVQ, Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9510965,
    longitude: 7.4447383,
  },
  {
    id: 'c131',
    name: 'Keek pharmacy',
    lga: 'FCT',
    address:
      '50 Ebitu Ukiwe St 50 Ebitu Ukiwe St, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0695178,
    longitude: 7.4320218,
  },
  {
    id: 'c132',
    name: 'Kenzee Pharmacy and Stores',
    lga: 'FCT',
    address:
      'Abm Plaza 6 A.E. Ekukinam St, Mabushi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0665812,
    longitude: 7.4460583,
  },
  {
    id: 'c133',
    name: 'Kevphine Pharmacy',
    lga: 'FCT',
    address:
      'Kevphine Pharmacy and Stores 12, Funmilayo R. Kuti Way, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.031449,
    longitude: 7.483519,
  },
  {
    id: 'c134',
    name: 'Kroaknel Pharmacy',
    lga: 'FCT',
    address:
      'Navy Quarters, Oduduwa St, Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1447599,
    longitude: 7.325955,
  },
  {
    id: 'c135',
    name: 'Lawcas pharmacy',
    lga: 'FCT',
    address:
      'Yasuha plaza 29 Adetokunbo Ademola Cres, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0735685,
    longitude: 7.4766493,
  },
  {
    id: 'c136',
    name: 'Lerof Pharmacy',
    lga: 'FCT',
    address:
      'Lerof Pharmacy Adjacent Total, Academy Karu Site, Off Igbo Road, Karu, Karu, Abuja, Federal Capital Territory 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0082414,
    longitude: 7.5584643,
  },
  {
    id: 'c137',
    name: 'LILIFIED PHARMACY',
    lga: 'FCT',
    address:
      'SHOP 1, SUNNYVALE HOMES MALL, Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9862094,
    longitude: 7.4474457,
  },
  {
    id: 'c138',
    name: 'Lo-ella Pharmacy',
    lga: 'FCT',
    address:
      'Lo-Ella Pharmacy And Stores 17 Amazon St, Maitama, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.099039,
    longitude: 7.4840747,
  },
  {
    id: 'c139',
    name: 'Lo-ella Pharmacy',
    lga: 'FCT',
    address:
      '25 Jos St 25 Jos St, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0317743,
    longitude: 7.4799726,
  },
  {
    id: 'c140',
    name: 'Lydacon pharmacy and stores',
    lga: 'FCT',
    address:
      'Lydacon Pharmaceutical & Store Mararaba Keffi Express Way, 2HHJ+7W5, Mararaba, New Karu 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.02816,
    longitude: 7.58229,
  },
  {
    id: 'c141',
    name: 'MAC-CHIZ PHARMACY AND STORES LTD KUJE',
    lga: 'FCT',
    address:
      'Mac-Chiz Pharmacy And Stores Ltd Uwa Cl, Abuja 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.018316,
    longitude: 7.584608,
  },
  {
    id: 'c142',
    name: 'Maggio Pharmacy',
    lga: 'Nasarawa',
    address: '51 Karu 51 Karu, Mararaba, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0296889,
    longitude: 7.6113775,
  },
  {
    id: 'c143',
    name: 'Maima pharmacy',
    lga: 'FCT',
    address:
      'Adetokunbo Ademola Cres, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0768939,
    longitude: 7.4874809,
  },
  {
    id: 'c144',
    name: 'Mane Sol Pharmacy Ltd Asokoro',
    lga: 'FCT',
    address: '2G87+QW8, Asokoro, Extension 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0169125,
    longitude: 7.5148281,
  },
  {
    id: 'c145',
    name: 'Marvel Rock Pharmaceutical',
    lga: 'FCT',
    address:
      'Holy Spirit Catholic Church, Azhyapi, Byazhin-Across Kubwa, Abuja, F.C.T, Kubwa 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1538486,
    longitude: 7.3219648,
  },
  {
    id: 'c146',
    name: 'Marvel Rock Pharmacy',
    lga: 'FCT',
    address:
      '2 Franca Afegbua Cres 2 Franca Afegbua Cres, Apo, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9997641,
    longitude: 7.4822073,
  },
  {
    id: 'c147',
    name: 'MarvelRock Pharmacy Ltd',
    lga: 'FCT',
    address:
      'Navy Quarters, Oduduwa St, Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1447599,
    longitude: 7.325955,
  },
  {
    id: 'c148',
    name: 'Matteno medical and health stores',
    lga: 'FCT',
    address:
      'MATTENO MEDICAL AND HEALTH STORES BLOCK 5 PAMBWARA TRANSFORMER ROAD, Chibiri 900105, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8940691,
    longitude: 7.1860402,
  },
  {
    id: 'c149',
    name: 'Maxcare Pharmacy',
    lga: 'FCT',
    address:
      'Precious Estate Gaduwa District Gaduwa, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9822495,
    longitude: 7.460871,
  },
  {
    id: 'c150',
    name: 'Maxicare pharmacy',
    lga: 'FCT',
    address:
      'Abia House , Abuja Abia House , Abuja, First Ave, Wuse, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0663417,
    longitude: 7.4926636,
  },
  {
    id: 'c151',
    name: 'Maximum Pharmacy',
    lga: 'FCT',
    address:
      'Bendel Street Bendel St, Garki 1, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.035724,
    longitude: 7.477326,
  },
  {
    id: 'c152',
    name: 'Mc Dons Pharmacy',
    lga: 'FCT',
    address:
      'Abia House , Abuja Abia House , Abuja, First Ave, Wuse, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0663417,
    longitude: 7.4926636,
  },
  {
    id: 'c153',
    name: 'Meblink Pharmacy',
    lga: 'Nasarawa',
    address:
      'Meblink Pharmacy Ltd Along Abuja - Keffi Expy, Karu, Mararba 900101, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0309639,
    longitude: 7.5894758,
  },
  {
    id: 'c154',
    name: 'Medicare Marche Pharmacy Ltd',
    lga: 'FCT',
    address:
      '95 Trademore Av. 95 Trademore Av., Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9564015,
    longitude: 7.3702001,
  },
  {
    id: 'c155',
    name: 'Medificient Health Systems and Pharmacy',
    lga: 'Nasarawa',
    address: '24 Kabayi Rd 24 Kabayi Rd, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0411384,
    longitude: 7.5896759,
  },
  {
    id: 'c156',
    name: 'Medimed Pharmacy',
    lga: 'FCT',
    address:
      'MEDIMED Pharmacy Game City Plaza, 1st Avenue, Gwarinpa, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1064141,
    longitude: 7.4134949,
  },
  {
    id: 'c157',
    name: 'MEDIVIEW PHARMACY',
    lga: 'FCT',
    address: 'Lingu Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.071223,
    longitude: 7.4674425,
  },
  {
    id: 'c158',
    name: 'Medix clue pharmacy',
    lga: 'FCT',
    address: '8 Alexandria Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0847449,
    longitude: 7.4671604,
  },
  {
    id: 'c159',
    name: 'Medixal pharmacy',
    lga: 'FCT',
    address:
      'Medixal Pharmacy Suite 6, Essence Plaza, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0707961,
    longitude: 7.4570235,
  },
  {
    id: 'c160',
    name: 'Medixal Pharmacy',
    lga: 'FCT',
    address:
      'Suite 6, Essence Plaza, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0615331,
    longitude: 7.4874267,
  },
  {
    id: 'c161',
    name: 'Mendoza Medical & Super Store',
    lga: 'FCT',
    address:
      'Mendoza Medical & Super Store (HOUSE AGENT) Dogongada, amac road dogongada, Lokogoma Rd, Lokogoma, Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9740234,
    longitude: 7.4544355,
  },
  {
    id: 'c162',
    name: 'Metro Medicare Limited',
    lga: 'FCT',
    address:
      '45 Libreville Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.074729,
    longitude: 7.463175,
  },
  {
    id: 'c163',
    name: 'Miliamed/lcemat pharmacy',
    lga: 'FCT',
    address: 'Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1538486,
    longitude: 7.3219648,
  },
  {
    id: 'c164',
    name: 'Minaco Pharmacy and companies limited',
    lga: 'Nasarawa',
    address: '6FW9VV38+6F44, NO 8 ABDUL ZANGA WAY, Keffi 961101, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8531931,
    longitude: 7.8662718,
  },
  {
    id: 'c165',
    name: 'MOBRED PLUS PHARMACY',
    lga: 'FCT',
    address:
      'Suleiman Barau Road Suleiman Barau Rd, Madalla 910101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1938506,
    longitude: 7.1840628,
  },
  {
    id: 'c166',
    name: 'Modern Times Pharmacy',
    lga: 'FCT',
    address:
      'House B161, Penthouse Estate, Unity Dr, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9663136,
    longitude: 7.3819633,
  },
  {
    id: 'c167',
    name: 'Morning Sun Pharmacy',
    lga: 'FCT',
    address:
      'Jahi 1 Police station jahi 1, beside police station, Kado, Abuja 900001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0959536,
    longitude: 7.4380103,
  },
  {
    id: 'c168',
    name: 'Morning Sun Pharmacy LTD',
    lga: 'FCT',
    address: 'Bassa 902101, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9621708,
    longitude: 7.1292076,
  },
  {
    id: 'c169',
    name: 'MorningSUN Pharmacy, NIG LTD',
    lga: 'FCT',
    address: 'Kuje 900105, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8821438,
    longitude: 7.2275336,
  },
  {
    id: 'c170',
    name: 'Mubaraq Pharmacy',
    lga: 'FCT',
    address:
      'Global Plaza, Jabi Upstairs, Jabi, Abuja, Nigeria Obafemi Awolowo Way, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0621347,
    longitude: 7.4239831,
  },
  {
    id: 'c171',
    name: 'Muzdalifa Pharmacy Ltd',
    lga: 'FCT',
    address: 'W987+P99, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9167875,
    longitude: 7.3634844,
  },
  {
    id: 'c172',
    name: 'Nathan Bitok',
    lga: 'FCT',
    address:
      'St. John Paul II Catholic Church Guzape Abuja Plot 838 Alex Ibru Street, off Babagana Kingibe St, Guzape, Aso 900104, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0056382,
    longitude: 7.5163353,
  },
  {
    id: 'c173',
    name: 'Nazarene Pharmacy',
    lga: 'FCT',
    address:
      'NAZARENE PHARMACY & STORES SHOP C31 GWARIMPA ULTRA MODERN MARKET, KADO LIFE CAMP, near FISH MARKET, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0662662,
    longitude: 7.3954356,
  },
  {
    id: 'c174',
    name: 'Nearby Pharmacy',
    lga: 'FCT',
    address:
      'Pace Setters College 136 Idris Gidado St, Utako, Ankuru 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.055521,
    longitude: 7.4438364,
  },
  {
    id: 'c175',
    name: 'Nedumax pharmacy ltd',
    lga: 'Nasarawa',
    address: 'Shopping Center, One Man Village A234, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0148685,
    longitude: 7.6234522,
  },
  {
    id: 'c176',
    name: 'Needs Pharmacy',
    lga: 'FCT',
    address:
      'Needs Pharmacy Suite A1 Calvary Plaza, Old Karu Rd, Karu, Ado 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0170687,
    longitude: 7.5880517,
  },
  {
    id: 'c177',
    name: 'Neeleen Pharmacy',
    lga: 'FCT',
    address: '3CJV+MRJ, Mabushi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0817125,
    longitude: 7.4445156,
  },
  {
    id: 'c178',
    name: 'Nelcel Pharmacy',
    lga: 'FCT',
    address:
      'S Y plaza S Y plaza, 1st Avenue, Gwarinpa, 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1083836,
    longitude: 7.4170967,
  },
  {
    id: 'c180',
    name: 'Nesterglaz Pharmacy',
    lga: 'FCT',
    address: 'Block industry kurudu, Abuja 900109, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9425546,
    longitude: 7.5495881,
  },
  {
    id: 'c181',
    name: 'Nett Pharmacy Jabi',
    lga: 'FCT',
    address:
      'Jabi Lake Mall Bala Sokoto Wy, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0764391,
    longitude: 7.4253855,
  },
  {
    id: 'c182',
    name: 'New Sekemi Pharmacy',
    lga: 'FCT',
    address:
      'Trademore Estate. Apo 103 Oxford St, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9765413,
    longitude: 7.4885547,
  },
  {
    id: 'c183',
    name: 'Niveron Pharmacy and Healthcare Ltd',
    lga: 'FCT',
    address: 'phase 1, 24 Esu Jetta Rd, Ado 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9865333,
    longitude: 7.5603353,
  },
  {
    id: 'c184',
    name: 'Nolad Pharmacy and ALLIED COY LTD',
    lga: 'FCT',
    address:
      "ANAFARA'A PLAZA Anafara'a plaza, 3CQ5+JCW, 1st Avenue, opposite oando filling station, Gwarinpa, 900108, Federal Capital Territory",
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0891245,
    longitude: 7.4085714,
  },
  {
    id: 'c185',
    name: 'Nuwairah Pharmacy',
    lga: 'FCT',
    address:
      'Amssco Platinum City XCXG+PRC, Unnamed Road, Abuja 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9993049,
    longitude: 7.4270303,
  },
  {
    id: 'c186',
    name: 'Obetta Pharmacy',
    lga: 'FCT',
    address:
      '13 Onitsha Cres 13 Onitsha Cres, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0405218,
    longitude: 7.5054948,
  },
  {
    id: 'c187',
    name: 'Ogechi Kanma Pharmacy',
    lga: 'Nasarawa',
    address: 'Agwan 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0316057,
    longitude: 7.6344689,
  },
  {
    id: 'c188',
    name: 'Ollan B Pharmacy',
    lga: 'FCT',
    address:
      'Ollan B Pharmacy and Stores No 3 Akwanga Close By Ile Ife Off Emeka Anyanku Area 8, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0361191,
    longitude: 7.4927438,
  },
  {
    id: 'c189',
    name: 'Oluwatobi pharmacy',
    lga: 'FCT',
    address:
      'IJ hair beauty Stc shop, fct, Utako Ultra Modern Market, 188 queen Elizabeth line, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0664114,
    longitude: 7.4454982,
  },
  {
    id: 'c190',
    name: 'Pandrah Rx',
    lga: 'FCT',
    address:
      'Abia Line 3C6J+M45, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0616202,
    longitude: 7.4303484,
  },
  {
    id: 'c191',
    name: 'Passion Trust pharmacy',
    lga: 'FCT',
    address:
      'Adetokunbo Ademola Crescent Adetokunbo Ademola Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0768939,
    longitude: 7.4874809,
  },
  {
    id: 'c192',
    name: 'Pauster Pharmacy',
    lga: 'FCT',
    address:
      'Pauster Pharmacy and Stores Suite 4, Ibiye Plaza, Beside Zenith Bank, Mpape, Abuja, FCT, Mape 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1292779,
    longitude: 7.4912976,
  },
  {
    id: 'c193',
    name: 'Peach Pharmacy',
    lga: 'FCT',
    address:
      'Herbert Macaulay Way Herbert Macaulay Wy, Abuja, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0632382,
    longitude: 7.4730931,
  },
  {
    id: 'c194',
    name: 'Petra-Care Pharmacy Stores',
    lga: 'FCT',
    address:
      'Abuja Shopping Complex Abuja Shopping Complex, Funmilayo Ransome Kuti Road, off Tafawa Balewa Rd, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0315805,
    longitude: 7.4834161,
  },
  {
    id: 'c195',
    name: 'PHARMA DISPENSERS LIMITED',
    lga: 'FCT',
    address:
      '58 Harper Street, Wuse Zone 7 Neighborhood Centre, Zone 7, Wuse, Abuja 900001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0504291,
    longitude: 7.4586063,
  },
  {
    id: 'c196',
    name: 'PHARMACY HUT PAYGREENS',
    lga: 'FCT',
    address:
      'Zenith Bank - Wuse 2 65 Adetokunbo Ademola Cres, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0707827,
    longitude: 7.4830303,
  },
  {
    id: 'c197',
    name: 'PHARMAID PHARMACY ABUJA',
    lga: 'FCT',
    address:
      'Pharmaid Pharmacy Vale Mall, Sunnyvale Estate, VFX6+9G8, Sherete 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8984196,
    longitude: 7.4613191,
  },
  {
    id: 'c198',
    name: 'PHARMGATE PHARMACY',
    lga: 'FCT',
    address: '44 Gana St, Maitama, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0776303,
    longitude: 7.499621,
  },
  {
    id: 'c199',
    name: 'Pijag Clinic',
    lga: 'Nasarawa',
    address: 'Pijag Clinic Maternity 30 Timan Hl St, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0351299,
    longitude: 7.6025382,
  },
  {
    id: 'c200',
    name: 'Prime Pharmacy',
    lga: 'FCT',
    address:
      '1 Lord Lugard St 1 Lord Lugard St, Garki, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0471598,
    longitude: 7.5075382,
  },
  {
    id: 'c201',
    name: 'Prime Pharmacy Kubwa',
    lga: 'FCT',
    address: '26 Gado Nasko Rd, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1534098,
    longitude: 7.345005,
  },
  {
    id: 'c202',
    name: 'Prognosy Pharmacy Trademore II',
    lga: 'FCT',
    address: 'X956+FXF, Trademore Av., Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9564015,
    longitude: 7.3702001,
  },
  {
    id: 'c203',
    name: 'Prognosy Pharmacy Trademore Lugbe',
    lga: 'FCT',
    address:
      'Trademore Estate Trademore Estate, Lugbe 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9546788,
    longitude: 7.3719147,
  },
  {
    id: 'c204',
    name: 'Prognosy Pharmacy Wuse 2',
    lga: 'FCT',
    address:
      '154 Aminu Kano Cres 154 Aminu Kano Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.083656,
    longitude: 7.46967,
  },
  {
    id: 'c205',
    name: 'PVX (Pax Vobix Xclusive) Pharmacy Maraba',
    lga: 'Nasarawa',
    address: 'PVX Pharmacy Ltd 25 Kabayi Rd, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0336732,
    longitude: 7.5936543,
  },
  {
    id: 'c206',
    name: 'PVX(Pax Vobix Xclusive) Pharmacy Nyanya',
    lga: 'FCT',
    address:
      'NNPC Limited Filling station 20 A234, Karu, New Karu 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0222693,
    longitude: 7.5671664,
  },
  {
    id: 'c207',
    name: 'Pyramid Pharmacy',
    lga: 'FCT',
    address:
      '73 Samuel Ladoke Akintola Boulevard 73 Samuel Ladoke Akintola Boulevard, Street, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.020915,
    longitude: 7.4855361,
  },
  {
    id: 'c208',
    name: 'Qualihealth Pharmacy and stores Deo-gratias plaza',
    lga: 'FCT',
    address:
      'Deo Gracia plaza 3C8V+RR9, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0670483,
    longitude: 7.4446066,
  },
  {
    id: 'c209',
    name: 'Qualihealth Pharmacy Utako(Atlantic Mall)',
    lga: 'FCT',
    address:
      '482 Obafemi Awolowo Way 482 Obafemi Awolowo Way, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0651158,
    longitude: 7.4293519,
  },
  {
    id: 'c210',
    name: 'Rabboni Pharmacy limited',
    lga: 'FCT',
    address:
      'Rabboni Pharmacy Shop B3, Multipurpose Shopping Complex, Estate, Kado, Abuja, FCT, Jabi, Gwarinpa 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0795291,
    longitude: 7.4164425,
  },
  {
    id: 'c211',
    name: 'Rama pharmacy',
    lga: 'FCT',
    address:
      '2 Malanje St 2 Malanje St, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0678317,
    longitude: 7.471619,
  },
  {
    id: 'c212',
    name: 'Rassma Pharmacy',
    lga: 'FCT',
    address:
      'Rassma Pharmacy 2FC4+C6H, Durumi, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0210675,
    longitude: 7.4556136,
  },
  {
    id: 'c213',
    name: 'Redeem pharmacy ltd',
    lga: 'FCT',
    address:
      'Abia Line 3C6J+M45, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0616202,
    longitude: 7.4303484,
  },
  {
    id: 'c214',
    name: 'Redemption Pharmacy',
    lga: 'FCT',
    address:
      'Redemption Pharmacy- FHA Lugbe Phase One X9MC+JJ4, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9840095,
    longitude: 7.3715918,
  },
  {
    id: 'c215',
    name: 'Redemption Pharmacy and store',
    lga: 'FCT',
    address:
      'Redemption Pharmacy- Fha Lugbe Phase One Lugbe, Abuja 102273, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9640864,
    longitude: 7.3813708,
  },
  {
    id: 'c216',
    name: 'Revans Pharmaceuticals',
    lga: 'FCT',
    address:
      'Revans Pharmaceutical Co Madalla 901101, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1162319,
    longitude: 7.2565781,
  },
  {
    id: 'c217',
    name: 'Rickmen Pharmacy',
    lga: 'FCT',
    address:
      '24 Ebitu Ukiwe St 24 Ebitu Ukiwe St, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0695178,
    longitude: 7.4320218,
  },
  {
    id: 'c218',
    name: 'Rock ville pharmacy',
    lga: 'FCT',
    address:
      'Abia House , Abuja Abia House , Abuja, First Ave, Wuse, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0663417,
    longitude: 7.4926636,
  },
  {
    id: 'c219',
    name: 'Rogana Pharmacy',
    lga: 'FCT',
    address: '40, 2 Ohafia Rd, Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1477928,
    longitude: 7.333007,
  },
  {
    id: 'c220',
    name: 'Royas Pharmacy',
    lga: 'FCT',
    address:
      'Landmark Plaza Yedseram Street, Ibrahim Babangida Way, Maitama, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0925735,
    longitude: 7.4997048,
  },
  {
    id: 'c221',
    name: 'Salamat Pharmacy',
    lga: 'FCT',
    address:
      'Nile University of Nigeria Plot 681, Cadastral Zone C, OO, Research & Institution Area, Airport Road, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9688213,
    longitude: 7.2611643,
  },
  {
    id: 'c222',
    name: 'Salvage Pharmacy',
    lga: 'Nasarawa',
    address: 'Mararaba XM98+3R3, Mararaba, Karu 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9676375,
    longitude: 7.6670469,
  },
  {
    id: 'c223',
    name: 'Sante Bene Rx',
    lga: 'FCT',
    address:
      'NNPC Apo Resettlement XFPV+HRR, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9865604,
    longitude: 7.4944833,
  },
  {
    id: 'c224',
    name: 'Sapphire Pharmacy',
    lga: 'FCT',
    address:
      '93 Obafemi Awolowo Way 93 Obafemi Awolowo Way, Mabushi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0651158,
    longitude: 7.4293519,
  },
  {
    id: 'c225',
    name: 'Sereni pharmacy',
    lga: 'FCT',
    address:
      'Road 1 & Road 2 Rd 1 & Rd 2, Kubwa 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0983745,
    longitude: 7.3831386,
  },
  {
    id: 'c226',
    name: 'ShowCare Pharmacy',
    lga: 'FCT',
    address:
      'LOKO 10 STORES opp. Fafu Estate, Abuja 900104, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.969236,
    longitude: 7.4760925,
  },
  {
    id: 'c227',
    name: 'Shushan Pharmacy LifeCamp',
    lga: 'FCT',
    address:
      'LightSpeed Colors Studios LifeCamp, Plot 963 Abubakar Koko Ave, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0812363,
    longitude: 7.3997501,
  },
  {
    id: 'c228',
    name: 'Silver Rose pharmacy',
    lga: 'FCT',
    address:
      'Abia House , Abuja Abia House , Abuja, First Ave, Wuse, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0663417,
    longitude: 7.4926636,
  },
  {
    id: 'c229',
    name: 'Sky Vic Pharmacy',
    lga: 'FCT',
    address:
      '7 Dutse St 7 Dutse St, Garki, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0169419,
    longitude: 7.4916557,
  },
  {
    id: 'c230',
    name: 'Skylark Pharmacy Keffi',
    lga: 'Nasarawa',
    address: 'Skylark Pharmacy RVXJ+3JP, Keffi 961101, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8477037,
    longitude: 7.881593,
  },
  {
    id: 'c231',
    name: 'Skylark Pharmacy Wuse Zone 3',
    lga: 'FCT',
    address:
      'D9, Sky Memorial Complex, Michael Okpara St, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0654932,
    longitude: 7.4575962,
  },
  {
    id: 'c232',
    name: 'Smart life Pharmacy',
    lga: 'FCT',
    address:
      'MAB Global Plaza 151 Obafemi Awolowo Way, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.062086,
    longitude: 7.4239351,
  },
  {
    id: 'c233',
    name: 'Solar Wide Pharmacy',
    lga: 'FCT',
    address:
      'Kade Street Kade St, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0831816,
    longitude: 7.466877,
  },
  {
    id: 'c234',
    name: 'St Luke De Basic Pharmacy',
    lga: 'FCT',
    address:
      'Dagiri Central Mosque Madam mercy road,dagiri, W3MP+36P, Gwagwalada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.932711,
    longitude: 7.0855835,
  },
  {
    id: 'c235',
    name: 'St. David Pharmacy (Abuja)',
    lga: 'FCT',
    address: '9 Cape Town, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0650231,
    longitude: 7.4729767,
  },
  {
    id: 'c236',
    name: 'STAR GOLD PHARMACY & STORES LTD',
    lga: 'FCT',
    address:
      'Gwagalada Central Mosque W3VJ+52X, Gwagwalada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9429945,
    longitude: 7.0801161,
  },
  {
    id: 'c237',
    name: 'Strands Pharmacy',
    lga: 'FCT',
    address: 'Hamza Abdullahi Rd, Kubwa, 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1441377,
    longitude: 7.3162219,
  },
  {
    id: 'c238',
    name: 'STRONG TOWER PHARMACEUTICAL',
    lga: 'FCT',
    address:
      'Chief Palace Tungan Maje 354V+CMQ, Anagada 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0560394,
    longitude: 7.1942527,
  },
  {
    id: 'c239',
    name: "STT DAVID'S PHARMACY",
    lga: 'FCT',
    address: '9 Cape Town, Wuse, Abuja 900288, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0650231,
    longitude: 7.4729767,
  },
  {
    id: 'c240',
    name: 'Sunamot Pharmacy',
    lga: 'FCT',
    address:
      'Aco Housing Estate Off Airport Rd, Lugbe 900102, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9299093,
    longitude: 7.3279718,
  },
  {
    id: 'c241',
    name: 'SUNCEL PHARMACY',
    lga: 'FCT',
    address: '38 3rd Ave 38 3rd Ave, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1000949,
    longitude: 7.412651,
  },
  {
    id: 'c242',
    name: 'Sunitem Pharmacy',
    lga: 'FCT',
    address: '68 Extension, Dawaki, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.132986,
    longitude: 7.3880964,
  },
  {
    id: 'c243',
    name: 'Sunmart Pharmacy & Stores',
    lga: 'FCT',
    address: '60 Panaf Dr, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1287838,
    longitude: 7.390832,
  },
  {
    id: 'c244',
    name: 'Super Pharma Ltd - Maitama',
    lga: 'FCT',
    address: '45 Gana St, Maitama, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0777571,
    longitude: 7.5001226,
  },
  {
    id: 'c245',
    name: 'Super Pharma Ltd - Wuse',
    lga: 'FCT',
    address:
      '741 Aminu Kano Cres, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0843349,
    longitude: 7.4675288,
  },
  {
    id: 'c246',
    name: 'Sycamore Pharmacy',
    lga: 'FCT',
    address: '76 4th Ave, Gwarinpa, 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1177616,
    longitude: 7.4097269,
  },
  {
    id: 'c247',
    name: 'Taonet Pharmacy',
    lga: 'FCT',
    address:
      'Taonet Pharmacy Ltd 74, Abuja Electricity Distribution Company (AEDC), opposite Old, Abuja 902101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9428618,
    longitude: 7.0881605,
  },
  {
    id: 'c248',
    name: 'Tarei Pharmacy',
    lga: 'FCT',
    address:
      'Deo Gracia plaza 3C8V+RR9, Utako, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0670483,
    longitude: 7.4446066,
  },
  {
    id: 'c249',
    name: 'Tec-Star Pharmacy and Stores',
    lga: 'FCT',
    address:
      'TEC-STAR PHARMACY & STORES LTD 2 Uwa Close, By Ezekiel Gomos Street, Before FIRS Office, off Abuja-Keffi Rd, Karu, Mararaba 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0182197,
    longitude: 7.5843873,
  },
  {
    id: 'c250',
    name: 'Terin Pharmacy',
    lga: 'FCT',
    address:
      'Nile University of Nigeria Plot 681, Cadastral Zone C, OO, Research & Institution Area, Airport Road, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9688213,
    longitude: 7.2611643,
  },
  {
    id: 'c251',
    name: 'Tonia Pharmacy Aminu Kano',
    lga: 'FCT',
    address:
      '87 Aminu Kano Cres 87 Aminu Kano Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.083656,
    longitude: 7.46967,
  },
  {
    id: 'c252',
    name: 'Tonia Pharmacy Buhari Way',
    lga: 'FCT',
    address:
      'Tswanya Center Tswanya Center, Mohammadu Buhari Way, Garki 2, Abuja 900103, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0307488,
    longitude: 7.4970615,
  },
  {
    id: 'c253',
    name: 'Tonia pharmacy Business District',
    lga: 'FCT',
    address:
      '270 Mohammadu Buhari Way, Central Business District, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0527874,
    longitude: 7.4791544,
  },
  {
    id: 'c254',
    name: 'Tonia pharmacy Gwarinpa',
    lga: 'FCT',
    address:
      'The Capital Hub, Ahmadu Bello Way, Kado, Wuse 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0896898,
    longitude: 7.4500519,
  },
  {
    id: 'c255',
    name: 'Tonia Pharmacy Maitama',
    lga: 'FCT',
    address:
      'Yedseram Street, Ibrahim Babangida Way, Maitama, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0855517,
    longitude: 7.4942576,
  },
  {
    id: 'c256',
    name: 'Tonyberries Pharmacy',
    lga: 'FCT',
    address:
      'ECWA Church off Bwari Road, Buntu, 79PH+6CH, Bwari 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.2855684,
    longitude: 7.3785989,
  },
  {
    id: 'c257',
    name: 'TOP NOTCH PHARMACY',
    lga: 'FCT',
    address:
      'Sabon-Gari Road Sabon-Gari Rd, Bwari 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.2776021,
    longitude: 7.3788076,
  },
  {
    id: 'c258',
    name: 'Topmed pharmacy',
    lga: 'FCT',
    address:
      '79 Adetokunbo Ademola Cres 79 Adetokunbo Ademola Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0768939,
    longitude: 7.4874809,
  },
  {
    id: 'c259',
    name: 'Total Trust Pharmacy',
    lga: 'FCT',
    address:
      'Total Trust Pharmacy 38 Old Karu Rd, Mararaba, Abuja 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0103013,
    longitude: 7.583167,
  },
  {
    id: 'c260',
    name: 'Trinity Pharmacy and Stores',
    lga: 'Nasarawa',
    address: 'Nasarawa road, Keffi 961101, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.8471213,
    longitude: 7.8776023,
  },
  {
    id: 'c261',
    name: 'Trovela Pharmacy and Stores',
    lga: 'FCT',
    address: 'Arab Rd, Kubwa, Abuja 901101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1563016,
    longitude: 7.3099986,
  },
  {
    id: 'c262',
    name: 'Udencare Pharmacy',
    lga: 'FCT',
    address:
      'SUITE 01 TAJLIFESTYLE MALL 1 ATARABA STREET, OFF Kampala St, Wuse 2, Abuja 900001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0768605,
    longitude: 7.4805458,
  },
  {
    id: 'c263',
    name: 'Ulti pharm Pharmacy',
    lga: 'FCT',
    address:
      '20 Aminu Kano Cres 20 Aminu Kano Cres, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.083656,
    longitude: 7.46967,
  },
  {
    id: 'c264',
    name: 'Unnex Pharmacy Wuye',
    lga: 'FCT',
    address:
      'Off Idris Gidado, 3C3V+QFM, road, Wuye, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0495044,
    longitude: 7.446421,
  },
  {
    id: 'c265',
    name: 'Urah Pharmacy',
    lga: 'FCT',
    address:
      'Binos Plaza Plot 23 suite 200 Palmview Estate, Lokogoma, Abuja 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9718862,
    longitude: 7.4709914,
  },
  {
    id: 'c266',
    name: 'Urah Pharmacy Kado',
    lga: 'FCT',
    address:
      'Kado Conoil Station 21 A.E. Ekukinam St, Jabi, Abuja 900108, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0770655,
    longitude: 7.4132586,
  },
  {
    id: 'c267',
    name: 'Valudrug Rx',
    lga: 'FCT',
    address:
      '528 Aminu Kano Cres 528 Aminu Kano Cres, Wuse 2, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.083656,
    longitude: 7.46967,
  },
  {
    id: 'c268',
    name: 'Visa Pharmacy and Stores ltd',
    lga: 'FCT',
    address:
      'Visa Pharmacy And Stores Ltd. Gwagwalada 902101, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9466061,
    longitude: 7.1023498,
  },
  {
    id: 'c269',
    name: 'Wandana Pharm. Ltd',
    lga: 'Nasarawa',
    address: '15 Calvary Rd 15 Calvary Rd, Ado 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.042393,
    longitude: 7.595639,
  },
  {
    id: 'c270',
    name: 'Weggi Pharmacy',
    lga: 'FCT',
    address:
      'Living Faith Church, Maitama Extension, Mpape, Abuja Alpine Baulevard, Maitama Extension, Mpape Junction, 3FQV+79C, Maitama, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0881875,
    longitude: 7.4933906,
  },
  {
    id: 'c271',
    name: 'Yusuf Illiya Pharmacy',
    lga: 'Nasarawa',
    address: 'Sabon Kasuwa Market 4WFV+GHX, Gitata 961106, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1238609,
    longitude: 7.943995,
  },
  {
    id: 'c272',
    name: 'Zagbayi pharmacy',
    lga: 'FCT',
    address:
      '1966 Maputo St 1966 Maputo St, Wuse, Abuja 904101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0605883,
    longitude: 7.4688256,
  },
  {
    id: 'c273',
    name: 'Zalek Pharmacy',
    lga: 'Nasarawa',
    address: 'XM3F+3G7, New Nyanya 961105, Nasarawa',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9526625,
    longitude: 7.6737969,
  },
  {
    id: 'c274',
    name: 'Zinni Pharmacy Ltd.',
    lga: 'FCT',
    address:
      'Lugbe Lugbe abuja Federal Capital Territory NG, Lugbe 900107, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.9640864,
    longitude: 7.3813708,
  },
  {
    id: 'c275',
    name: 'Zirafyn Pharmacy',
    lga: 'FCT',
    address:
      'Mopol Junction Football Field 2HHG+7W6, 8 A234, Karu, Abuja 900101, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.0274776,
    longitude: 7.5771996,
  },
  {
    id: 'c276',
    name: 'Zurasuph',
    lga: 'FCT',
    address:
      'Nill House 50th, 4th Ave, Gwarinpa Estate, Abuja 908001, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.1173648,
    longitude: 7.4069837,
  },
  {
    id: 'c278',
    name: 'Jachdez Pharmacy',
    lga: 'FCT',
    address: 'Plot AT175, Third gate, Apo mechanic estate, Apo, Abuja',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.953657713,
    longitude: 7.49767869,
  },
  {
    id: 'c279',
    name: 'Adina pharmacy',
    lga: 'FCT',
    address:
      '13378 51st Rd, Fct, Lugbe 900107, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.984491829,
    longitude: 7.36050569,
  },
  {
    id: 'c280',
    name: 'Drug track Pharmacy',
    lga: 'FCT',
    address: 'Shop A04 Lugbe Pharmacy',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.991322225,
    longitude: 7.35508838,
  },
  {
    id: 'c281',
    name: 'Medixal Pharmacy',
    lga: 'FCT',
    address:
      'Suite 10, Zone B Shopping center Legislative Quarters 1 Nwafor Orizu St, off Aderemi Adesoji, Abuja 900104, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.015891709,
    longitude: 7.47883108,
  },
  {
    id: 'c282',
    name: 'Yellowmed pharmacy',
    lga: 'FCT',
    address:
      'THIRD GATE, APO MECHANIC VILLAGE, SHOP AT-500, APO, opp. JUDE MANU GARDEN, 900110, Federal Capital Territory',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.955191646,
    longitude: 7.50050219,
  },
  {
    id: 'c283',
    name: 'Chidivac Pharmacy',
    lga: 'FCT',
    address: 'HOUSE 41 A PHASE 2, Lugbe, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.988274798,
    longitude: 7.3624039,
  },
  {
    id: 'c284',
    name: 'Deonahs Pharmacy & Stores',
    lga: 'FCT',
    address:
      'Ebeanor Supermarket Rd, Abdulsalami Abubakar Rd, Abuja 930001, Federal Capital Territory, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 8.994826532,
    longitude: 7.46898046,
  },
  {
    id: 'c285',
    name: 'Solvers Pharmacy and Stores',
    lga: 'Nasarawa',
    address: '2HGP+JCV, Abacha Rd, New karu 900101, federal Capital Abuja.',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.026910082,
    longitude: 7.5866919,
  },
  {
    id: 'c286',
    name: 'Gentle Heart Pharmacy and Store',
    lga: 'Nasarawa',
    address:
      'Beside Yahuza Suya, 36 Old Karu Rd, Mararaba, Karu, Nasarawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.024894823,
    longitude: 7.59679857,
  },
  {
    id: 'c287',
    name: 'Ifytex Pharmacy Store',
    lga: 'Nasarawa',
    address: 'Aunty Alice Road 2JF2+V23',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.01712555,
    longitude: 7.60159224,
  },
  {
    id: 'c288',
    name: 'Vunoklang Pharmacy ( Hayingada Girei)',
    lga: 'Adamawa',
    address: '8F2J+624, Jabura 652101, Adamawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.310021704,
    longitude: 12.4876105,
  },
  {
    id: 'c289',
    name: '⁠BMS Pharmacy',
    lga: 'Adamawa',
    address: '7FH5+W83, Jimeta, Adamawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.27987863,
    longitude: 12.4583102,
  },
  {
    id: 'c290',
    name: '⁠BJ Standard Pharmacy',
    lga: 'Adamawa',
    address:
      'Muhammad Mustafa Way Muhammad Mustafa Wy, Jimeta, Adamawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.279931467,
    longitude: 12.4458763,
  },
  {
    id: 'c291',
    name: 'AH Gambo Pharmacy',
    lga: 'Adamawa',
    address: '7FH4+FJC, Jimeta, Adamawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.278927188,
    longitude: 12.4565274,
  },
  {
    id: 'c292',
    name: '⁠Everwell Pharmacy',
    lga: 'Adamawa',
    address: '6FQ3+G8, Jimeta, Adamawa, Nigeria',
    days_of_immunization: '',
    hours_of_work: '',
    latitude: 9.239014674,
    longitude: 12.4537797,
  },
];
